/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CropArea: typeof import('./src/components/CropArea.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    GrowthStage: typeof import('./src/components/GrowthStage.vue')['default']
    HeaderCom: typeof import('./src/components/HeaderCom.vue')['default']
    HealthIndex: typeof import('./src/components/HealthIndex.vue')['default']
    ProductHistory: typeof import('./src/components/ProductHistory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
